apiVersion: v1
kind: Service
metadata:
  name: retail-app-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.app.service.type }}

  selector:
    app: retail

  ports:
  - port: {{ .Values.app.service.port }}
    targetPort: {{ .Values.app.service.port }}
    protocol: TCP