apiVersion: v1
kind: Secret
metadata:
  name: retail-app-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  EMAIL_USER: {{ .Values.secret.EMAIL_USER | b64enc }}
  EMAIL_PASS: {{ .Values.secret.EMAIL_PASS | b64enc }}